/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ccasw_claim_registration.java
 *
 * Created on Jan 21, 2013, 6:41:47 PM
 */

package cc_aswata;

//import static cc_aswata.ccasw_View_Policy.CCanj;
//import static cc_aswata.ccasw_View_Policy.detilcus;
//import static cc_aswata.ccasw_View_Policy.html;
//import static cc_aswata.ccasw_View_Policy.ws1;
//import static cc_aswata.ccasw_View_Policy.wsid;
//import static cc_aswata.ccasw_View_Policy.wsstt;
import java.awt.event.*;
import java.awt.Event.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alienware
 */
public class ccasw_claim_registration extends javax.swing.JFrame {
    private static String condition,branchid,typofid,docid,causeid,statusid,claimInfoCol;
    private static int casco=0,tpl=0,lifeIns=0,paDri=0,paPass=0,pll=0,biayaDerek=0;
    private static String cus[]=new String[21];
    public static String cobid1 = "";
    public static int Form=0,wsid=1,wsid1=1,wsstt=0;
    public static boolean ws=false,ws1=false,action=false,action1=false;
    Timer wsws;

    /** Creates new form ccasw_claim_registration */
    public ccasw_claim_registration() {
        initComponents();        
        tblPolicy.setModel(tabcus1);
        tabcus1.setRowCount(0);
        tbcus(tblPolicy,new int []{40,200,150,150,120,150,100,120});
        setMaximumSize(new java.awt.Dimension(1024,768));
        branch();statusClaim();couseOf();typeOf();tpl();
    }

    public static ContactCenterASWATA CCanj;
    public ccasw_claim_registration(ContactCenterASWATA ccanj){
        this();
        this.CCanj=ccanj;
    }
    public static ccasw_Police_Detail PoDe;
    public ccasw_claim_registration(ccasw_Police_Detail pode){
        this();
        this.PoDe=pode;
    }
    private ccasw_ProgressBar Prg;
    public ccasw_claim_registration(ccasw_ProgressBar prg){
        this();
        this.Prg=prg;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void tbcus(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for (int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc=tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(18);
        }
    }
    public static javax.swing.table.DefaultTableModel getDefaultTabelcus1(){
        return new javax.swing.table.DefaultTableModel(
                new Object [][]{},
                new String [] {"No.","THE INSURED","C.O.B","POLICY NO.","COVER NOTE NO.","OPEN COVER NO.","CERTIFICATE NO.","POLICY ORDER NO.","INCOMING REQ. NO."}){
                boolean[] canEdit=new boolean[]{
                    false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
                };
                public boolean isCellEditable(int rowIndex, int columnIndex){
                        return canEdit[columnIndex];
                }
        };
    }
    public static javax.swing.table.DefaultTableModel tabcus1=getDefaultTabelcus1();
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRcvd = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox();
        cbBranch = new javax.swing.JComboBox();
        txtRegNo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolicy = new javax.swing.JTable();
        btnSrchPolicy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ckBiayaDerek = new javax.swing.JCheckBox();
        ckCasco = new javax.swing.JCheckBox();
        ckTpl = new javax.swing.JCheckBox();
        ckLifeIns = new javax.swing.JCheckBox();
        ckPaDriver = new javax.swing.JCheckBox();
        ckPaPassenger = new javax.swing.JCheckBox();
        ckPll = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        txtRefNo = new javax.swing.JTextField();
        txtReportedBy = new javax.swing.JTextField();
        dtLoss = new com.toedter.calendar.JDateChooser();
        cbCause = new javax.swing.JComboBox();
        cbTpl = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtLossLocation = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtChronology = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtRemark = new javax.swing.JTextArea();
        cbType = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        txtTimeOf = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1004, 966));
        jPanel1.setPreferredSize(new java.awt.Dimension(1004, 1266));
        jPanel1.setLayout(null);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER CLAIM REGISTRATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1010, 20);

        jPanel2.setLayout(null);

        jLabel2.setFont(jLabel2.getFont().deriveFont((float)11));
        jLabel2.setText("BRANCH CLAIM REG.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 70, 120, 20);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, 11));
        jLabel3.setText("01. GENERAL");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 120, 20);

        jLabel4.setFont(jLabel4.getFont().deriveFont((float)11));
        jLabel4.setText("REGISTRATION NO.");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 40, 120, 20);

        jLabel5.setFont(jLabel5.getFont().deriveFont((float)11));
        jLabel5.setText("STATUS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(480, 40, 100, 20);

        jLabel6.setFont(jLabel6.getFont().deriveFont((float)11));
        jLabel6.setText("RECEIVED BY");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(480, 70, 100, 20);

        jLabel7.setFont(jLabel7.getFont().deriveFont((float)11));
        jLabel7.setText(" : ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(130, 40, 10, 20);

        jLabel8.setFont(jLabel8.getFont().deriveFont((float)11));
        jLabel8.setText(" : ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(130, 70, 10, 20);

        jLabel9.setFont(jLabel9.getFont().deriveFont((float)11));
        jLabel9.setText(" : ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(580, 40, 10, 20);

        jLabel10.setFont(jLabel10.getFont().deriveFont((float)11));
        jLabel10.setText(" : ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(580, 70, 10, 20);

        txtRcvd.setFont(txtRcvd.getFont().deriveFont((float)11));
        jPanel2.add(txtRcvd);
        txtRcvd.setBounds(590, 70, 340, 25);

        cbStatus.setFont(cbStatus.getFont().deriveFont((float)11));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbStatus);
        cbStatus.setBounds(590, 40, 340, 25);

        cbBranch.setFont(cbBranch.getFont().deriveFont((float)11));
        cbBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbBranch);
        cbBranch.setBounds(140, 70, 320, 25);

        txtRegNo.setFont(txtRegNo.getFont().deriveFont((float)11));
        jPanel2.add(txtRegNo);
        txtRegNo.setBounds(140, 40, 320, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 40, 940, 100);

        jPanel3.setLayout(null);

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD, 11));
        jLabel11.setText("02. POLICY INFORMATION");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 10, 200, 20);

        tblPolicy.setFont(tblPolicy.getFont().deriveFont((float)11));
        tblPolicy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPolicy);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 920, 140);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 150, 940, 180);

        btnSrchPolicy.setFont(btnSrchPolicy.getFont().deriveFont(btnSrchPolicy.getFont().getStyle() | java.awt.Font.BOLD, 11));
        btnSrchPolicy.setText("SEARCH POLICY");
        btnSrchPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchPolicyActionPerformed(evt);
            }
        });
        jPanel1.add(btnSrchPolicy);
        btnSrchPolicy.setBounds(50, 330, 130, 24);

        jPanel4.setLayout(null);

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getStyle() | java.awt.Font.BOLD, 11));
        jLabel12.setText("03. LOSS INFORMATION");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 10, 200, 20);

        jLabel13.setFont(jLabel13.getFont().deriveFont((float)11));
        jLabel13.setText("REPORTED BY *");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 40, 120, 20);

        jLabel14.setFont(jLabel14.getFont().deriveFont((float)11));
        jLabel14.setText("PHONE NO.");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 70, 120, 20);

        jLabel15.setFont(jLabel15.getFont().deriveFont((float)11));
        jLabel15.setText(" : ");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(130, 40, 10, 20);

        jLabel16.setFont(jLabel16.getFont().deriveFont((float)11));
        jLabel16.setText(" : ");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(130, 70, 10, 20);

        jLabel17.setFont(jLabel17.getFont().deriveFont((float)11));
        jLabel17.setText("PLA REF. NO.");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(10, 100, 120, 20);

        jLabel18.setFont(jLabel18.getFont().deriveFont((float)11));
        jLabel18.setText("DATE OF LOSS *");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 130, 120, 20);

        jLabel19.setFont(jLabel19.getFont().deriveFont((float)11));
        jLabel19.setText(" : ");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(130, 100, 10, 20);

        jLabel20.setFont(jLabel20.getFont().deriveFont((float)11));
        jLabel20.setText(" : ");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(130, 130, 10, 20);

        jLabel21.setFont(jLabel21.getFont().deriveFont((float)11));
        jLabel21.setText("REGISTERED DATE");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(150, 160, 240, 20);

        jLabel22.setFont(jLabel22.getFont().deriveFont((float)11));
        jLabel22.setText("or DAMAGE OBJECT *");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(10, 210, 120, 20);

        jLabel23.setFont(jLabel23.getFont().deriveFont((float)11));
        jLabel23.setText(" : ");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(130, 160, 10, 20);

        jLabel24.setFont(jLabel24.getFont().deriveFont((float)11));
        jLabel24.setText(" : ");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(130, 190, 10, 20);

        jLabel25.setFont(jLabel25.getFont().deriveFont((float)11));
        jLabel25.setText("DESCRIPTION OF LOSS ");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(10, 190, 120, 20);

        jLabel26.setFont(jLabel26.getFont().deriveFont((float)11));
        jLabel26.setText("CAUSE OF LOSS *");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(10, 280, 120, 20);

        jLabel27.setFont(jLabel27.getFont().deriveFont((float)11));
        jLabel27.setText(" : ");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(130, 280, 10, 20);

        jLabel28.setFont(jLabel28.getFont().deriveFont((float)11));
        jLabel28.setText("TYPE OF LOSS *");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(10, 310, 120, 20);

        jLabel29.setFont(jLabel29.getFont().deriveFont((float)11));
        jLabel29.setText(" : ");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(130, 310, 10, 20);

        jLabel30.setFont(jLabel30.getFont().deriveFont((float)11));
        jLabel30.setText(" : ");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(130, 340, 10, 20);

        jLabel31.setFont(jLabel31.getFont().deriveFont((float)11));
        jLabel31.setText("LOSS AFFECTED *");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(10, 340, 120, 20);

        ckBiayaDerek.setFont(ckBiayaDerek.getFont().deriveFont((float)11));
        ckBiayaDerek.setText("BIAYA DEREK");
        ckBiayaDerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBiayaDerekActionPerformed(evt);
            }
        });
        jPanel4.add(ckBiayaDerek);
        ckBiayaDerek.setBounds(160, 460, 240, 20);

        ckCasco.setFont(ckCasco.getFont().deriveFont((float)11));
        ckCasco.setText("CASCO");
        ckCasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckCascoActionPerformed(evt);
            }
        });
        jPanel4.add(ckCasco);
        ckCasco.setBounds(160, 340, 61, 20);

        ckTpl.setFont(ckTpl.getFont().deriveFont((float)11));
        ckTpl.setText("TPL");
        ckTpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTplActionPerformed(evt);
            }
        });
        jPanel4.add(ckTpl);
        ckTpl.setBounds(160, 360, 43, 20);

        ckLifeIns.setFont(ckLifeIns.getFont().deriveFont((float)11));
        ckLifeIns.setText("LIFE INSURANCE");
        ckLifeIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckLifeInsActionPerformed(evt);
            }
        });
        jPanel4.add(ckLifeIns);
        ckLifeIns.setBounds(160, 380, 240, 20);

        ckPaDriver.setFont(ckPaDriver.getFont().deriveFont((float)11));
        ckPaDriver.setText("PA DRIVER");
        ckPaDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPaDriverActionPerformed(evt);
            }
        });
        jPanel4.add(ckPaDriver);
        ckPaDriver.setBounds(160, 400, 240, 20);

        ckPaPassenger.setFont(ckPaPassenger.getFont().deriveFont((float)11));
        ckPaPassenger.setText("PA PASSANGER");
        ckPaPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPaPassengerActionPerformed(evt);
            }
        });
        jPanel4.add(ckPaPassenger);
        ckPaPassenger.setBounds(160, 420, 240, 20);

        ckPll.setFont(ckPll.getFont().deriveFont((float)11));
        ckPll.setText("PLL");
        ckPll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPllActionPerformed(evt);
            }
        });
        jPanel4.add(ckPll);
        ckPll.setBounds(160, 440, 240, 20);

        jLabel32.setFont(jLabel32.getFont().deriveFont((float)11));
        jLabel32.setText("LOSS LOCATION *");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(10, 490, 120, 20);

        jLabel33.setFont(jLabel33.getFont().deriveFont((float)11));
        jLabel33.setText(" : ");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(130, 490, 10, 20);

        jLabel34.setFont(jLabel34.getFont().deriveFont((float)11));
        jLabel34.setText("CHRONOLOGY *");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(10, 580, 120, 20);

        jLabel35.setFont(jLabel35.getFont().deriveFont((float)11));
        jLabel35.setText(" : ");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(130, 580, 10, 20);

        jLabel36.setFont(jLabel36.getFont().deriveFont((float)11));
        jLabel36.setText(" : ");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(130, 670, 10, 20);

        jLabel37.setFont(jLabel37.getFont().deriveFont((float)11));
        jLabel37.setText("REMARK");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(10, 670, 120, 20);

        jLabel38.setFont(jLabel38.getFont().deriveFont((float)11));
        jLabel38.setText("COMMENT");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(10, 760, 120, 20);

        jLabel39.setFont(jLabel39.getFont().deriveFont((float)11));
        jLabel39.setText(" : ");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(130, 760, 10, 20);

        txtPhoneNo.setFont(txtPhoneNo.getFont().deriveFont((float)11));
        jPanel4.add(txtPhoneNo);
        txtPhoneNo.setBounds(150, 70, 200, 24);

        txtRefNo.setFont(txtRefNo.getFont().deriveFont((float)11));
        jPanel4.add(txtRefNo);
        txtRefNo.setBounds(150, 100, 300, 24);

        txtReportedBy.setFont(txtReportedBy.getFont().deriveFont((float)11));
        jPanel4.add(txtReportedBy);
        txtReportedBy.setBounds(150, 40, 300, 24);

        dtLoss.setDateFormatString("DD-MMM-yyyy HH:mm");
        dtLoss.setFont(dtLoss.getFont().deriveFont((float)11));
        jPanel4.add(dtLoss);
        dtLoss.setBounds(150, 130, 140, 24);

        cbCause.setFont(cbCause.getFont().deriveFont((float)11));
        cbCause.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cbCause);
        cbCause.setBounds(150, 280, 300, 24);

        cbTpl.setFont(cbTpl.getFont().deriveFont((float)11));
        cbTpl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTpl.setEnabled(false);
        jPanel4.add(cbTpl);
        cbTpl.setBounds(400, 360, 250, 25);

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane3.setViewportView(txtComment);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(150, 760, 760, 80);

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane4.setViewportView(txtDesc);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(150, 190, 760, 80);

        txtLossLocation.setColumns(20);
        txtLossLocation.setRows(5);
        jScrollPane5.setViewportView(txtLossLocation);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(150, 490, 760, 80);

        txtChronology.setColumns(20);
        txtChronology.setRows(5);
        jScrollPane6.setViewportView(txtChronology);

        jPanel4.add(jScrollPane6);
        jScrollPane6.setBounds(150, 580, 760, 80);

        txtRemark.setColumns(20);
        txtRemark.setRows(5);
        jScrollPane7.setViewportView(txtRemark);

        jPanel4.add(jScrollPane7);
        jScrollPane7.setBounds(150, 670, 760, 80);

        cbType.setFont(cbType.getFont().deriveFont((float)11));
        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cbType);
        cbType.setBounds(150, 310, 250, 24);

        jLabel40.setFont(jLabel40.getFont().deriveFont((float)11));
        jLabel40.setText("REGISTERED DATE");
        jPanel4.add(jLabel40);
        jLabel40.setBounds(10, 160, 120, 20);

        txtTimeOf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("h:mm"))));
        txtTimeOf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtTimeOf);
        txtTimeOf.setBounds(310, 130, 80, 24);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 360, 940, 860);

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getStyle() | java.awt.Font.BOLD, 11));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(890, 1220, 80, 24);

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
ccasw_Search_Policy srpolis = new ccasw_Search_Policy();
    private void btnSrchPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchPolicyActionPerformed
        // TODO add your handling code here:
        srpolis.setVisible(true);
        srpolis.Form = 5;
//        srpolis.txtNama.setText(txtcalnm.getText());
        srpolis.btnsrch.setEnabled(true);
    }//GEN-LAST:event_btnSrchPolicyActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        PoDe.btnClaim.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void ckTplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTplActionPerformed
        // TODO add your handling code here:
        if(ckTpl.isSelected()==true){
            cbTpl.setEnabled(true);
            tpl=1;
        }else{
            cbTpl.setEnabled(false);tpl=0;
        }
    }//GEN-LAST:event_ckTplActionPerformed
String dateOfLoss,RegDate,RegTime;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ws1=true;
        Date dt6 =dtLoss.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
        if(dt6!=null){                dateOfLoss = sdf.format(dt6);            }
        try{
            sql1 = "insert into ws_request set request_time=CURRENT_TIMESTAMP "
                    + ",username='" + CCanj.lbluser.getText() + "'"
                    + ",function_id=13"
                    + ",ws_params='\"comment\"-:-\""+txtComment.getText()+"\"-,-" +
                        "\"cobId\"-:-\"\"-,-" +
                        "\"tplType\"-:-\""+cbTpl.getSelectedItem()+"\"-,-" +
                        "\"remark\"-:-\""+txtRemark.getText()+"\"-,-" +
                        "\"tplFlag\"-:-\""+tpl+"\"-,-" +
                        "\"plaRefNo\"-:-\""+txtRefNo.getText()+"\"-,-" +
                        "\"phoneNo\"-:-\""+txtPhoneNo.getText()+"\"-,-" +
                        "\"cascoFlag\"-:-\""+casco+"\"-,-" +
                        "\"lifeFlag\"-:-\""+lifeIns+"\"-,-" +
                        "\"pllFlag\"-:-\""+pll+"\"-,-" +
                        "\"craneFlag\"-:-\""+biayaDerek+"\"-,-" +
                        "\"userName\"-:-\""+CCanj.lbluser.getText()+"\"-,-" +
                        "\"typeOfLossId\"-:-\""+typofid+"\"-,-" +
                        "\"typeOfLossDesc\"-:-\""+cbType.getSelectedItem()+"\"-,-" +
                        "\"registrationType\"-:-\"\"-,-" +
                        "\"registrationNo\"-:-\"\"-,-" +
                        "\"branchIdReg\"-:-\""+branchid+"\"-,-" +
                        "\"reportedBy\"-:-\""+txtReportedBy.getText()+"\"-,-" +
                        "\"receivedBy\"-:-\""+txtRcvd.getText()+"\"-,-" +
                        "\"dateOfLoss\"-:-\""+dateOfLoss+"\"-,-" +
                        "\"registeredDate\"-:-\""+RegDate+"\"-,-" +
                        "\"lossDescription\"-:-\""+txtDesc.getText()+"\"-,-" +
                        "\"causeOfLossId\"-:-\""+causeid+"\"-,-" +
                        "\"lossLocation\"-:-\""+txtLossLocation.getText()+"\"-,-" +
                        "\"chronology\"-:-\""+txtChronology.getText()+"\"-,-" +
                        "\"paDriverFlag\"-:-\""+paDri+"\"-,-" +
                        "\"paPassengerFlag\"-:-\""+paPass+"\"-,-" +
                        "\"claimCenter\"-:-\"\"-,-" +
                        "\"jabodetabek\"-:-\"\"-,-" +
                        "\"policyClaimInfoCollection\"-:-["+claimInfoCol+"]-,-" +
                        "\"statusClaim\"-:-\""+cbStatus.getSelectedIndex()+"\"-,-" +
                        "\"timeOfLoss\"-:-\""+txtTimeOf.getText()+"\"-,-" +
                        "\"registeredTime\"-:-\""+RegTime+"\"-,-" +
                        "\"causeOfLossDesc\"-:-\""+cbCause.getSelectedItem()+"\"-,-" +
                        "\"selectedTypeofLoss\"-:-\""+typofid+"'"
                    + "";
            CCanj.jconn.SQLExecute(sql1, CCanj.conn);
            sqlid = "select distinct last_insert_id() from ws_request";
            rs = CCanj.jconn.SQLExecuteRS(sqlid, CCanj.conn);
            while (rs.next()) {
                wsid1 = Integer.parseInt(rs.getString(1));
                ws = true;
            }
            System.out.println("\n wsid1 : "+wsid1);
            wsid=wsid1;
            request();
        }catch (SQLException ex) {
            Logger.getLogger(ccasw_Search_customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getTablePolicy(){
        claimInfoCol="";
        if(tabcus1.getRowCount()!=0){
            int loop=0;
            while(loop != tabcus1.getRowCount()){
                loop++;
                if(claimInfoCol.equals("")){
                    claimInfoCol=claimInfoCol+"|";
                }
                claimInfoCol=claimInfoCol="{\"cobId\"-:-\"301\"-,-" +
                            "	\"no\"-:-\""+(String)tblPolicy.getValueAt(loop,tblPolicy.getTableHeader().getColumnModel().getColumnIndex("No."))+"\"-,-" +
                            "	\"cob\"-:-\""+(String)tblPolicy.getValueAt(loop,tblPolicy.getTableHeader().getColumnModel().getColumnIndex("C.O.B"))+"\"-,-" +
                            "	\"incomingRequestNumber\"-:-\"\"-,-" +
                            "	\"policyNumber\"-:-\""+(String)tblPolicy.getValueAt(loop,tblPolicy.getTableHeader().getColumnModel().getColumnIndex("POLICY NO."))+"\"-,-" +
                            "	\"policyOrderNumber\"-:-\"null\"-,-" +
                            "	\"certificateNumber\"-:-\"null\"-,-" +
                            "	\"coverNoteNumber\"-:-\"null\"-,-" +
                            "	\"openCoverNumber\"-:-\"null\"-,-" +
                            "	\"theInsured\"-:-\""+(String)tblPolicy.getValueAt(loop,tblPolicy.getTableHeader().getColumnModel().getColumnIndex("THE INSURED"))+"\"}" ;
            }
//            claimInfoCol="["+claimInfoCol+"]";
        }
    }
    private void ckCascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckCascoActionPerformed
        // TODO add your handling code here:
        if(ckCasco.isSelected()==true){
            casco=1;
        }else{
            casco=0;
        }
    }//GEN-LAST:event_ckCascoActionPerformed

    private void ckLifeInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckLifeInsActionPerformed
        // TODO add your handling code here:
        if(ckLifeIns.isSelected()==true){
            lifeIns=1;
        }else{
            lifeIns=0;
        }
    }//GEN-LAST:event_ckLifeInsActionPerformed

    private void ckPaDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPaDriverActionPerformed
        // TODO add your handling code here:
        if(ckPaDriver.isSelected()==true){
            paDri=1;
        }else{
            paDri=0;
        }
    }//GEN-LAST:event_ckPaDriverActionPerformed

    private void ckPaPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPaPassengerActionPerformed
        // TODO add your handling code here:
        if(ckPaPassenger.isSelected()==true){
            paPass=1;
        }else{
            paPass=0;
        }
    }//GEN-LAST:event_ckPaPassengerActionPerformed

    private void ckPllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPllActionPerformed
        // TODO add your handling code here:
        if(ckPll.isSelected()==true){
            pll=1;
        }else{
            pll=0;
        }
    }//GEN-LAST:event_ckPllActionPerformed

    private void ckBiayaDerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBiayaDerekActionPerformed
        // TODO add your handling code here:
        if(ckBiayaDerek.isSelected()==true){
            biayaDerek=1;
        }else{
            biayaDerek=0;
        }
    }//GEN-LAST:event_ckBiayaDerekActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ccasw_claim_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSrchPolicy;
    private javax.swing.JComboBox cbBranch;
    private javax.swing.JComboBox cbCause;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JComboBox cbTpl;
    private javax.swing.JComboBox cbType;
    private javax.swing.JCheckBox ckBiayaDerek;
    private javax.swing.JCheckBox ckCasco;
    private javax.swing.JCheckBox ckLifeIns;
    private javax.swing.JCheckBox ckPaDriver;
    private javax.swing.JCheckBox ckPaPassenger;
    private javax.swing.JCheckBox ckPll;
    private javax.swing.JCheckBox ckTpl;
    private com.toedter.calendar.JDateChooser dtLoss;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblPolicy;
    private javax.swing.JTextArea txtChronology;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextArea txtLossLocation;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtRcvd;
    private javax.swing.JTextField txtRefNo;
    private javax.swing.JTextField txtRegNo;
    private javax.swing.JTextArea txtRemark;
    private javax.swing.JTextField txtReportedBy;
    private javax.swing.JFormattedTextField txtTimeOf;
    // End of variables declaration//GEN-END:variables

    private static String sql,sql1,sqlid;
    private static ResultSet rs,rs1;

    Action wsinbound = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            webservice();
        }
    };

    private void webservice(){
        try{
            sql="select ws_status from ws_request where request_id="+wsid+" ";
            rs1=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
            while(rs1.next()){
                wsstt=Integer.parseInt(rs1.getString(1));
            }
            System.out.println("\n status ws : "+wsstt+" dari ws id : "+wsid);
            process();
            if(wsstt==2){
                if(ws1==false){  }else{ dispose();}
                wsws.stop();Prg.dialog.hide();
            }else if(wsstt==3){
                wsws.stop();
                Prg.dialog.hide();
                JOptionPane.showMessageDialog(null, "Data not found","Error!!!",JOptionPane.WARNING_MESSAGE);
                dispose();
            }
            ws1=false;
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }
    private void branch(){
        cbBranch.removeAllItems();
        try{
            sql="select name from _ws_branch where regional_id <> branch_id or branch_id=87 order by branch_id ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbBranch.addItem(rs.getString(1));
            }
            cbBranch.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);
        }
    }
    public void request(){
        if(ws=true&&wsid!=-1){
            Prg.value=0;
            wsws.start();
//            dialog.show();
            Prg.dialog.show();
            Prg.pasw.setValue(0);
        }
    }
    public void process(){
        Prg.value=Prg.pasw.getValue() + 10;
        if(Prg.value ==100){
            Prg.value=0;
        }
        Prg.pasw.setValue(Prg.value);
        if(Prg.dialog.isShowing()==false){
            wsws.stop();
        }
    }
    public static void cek(){
        if(Form==1){
//            btnEmbed.setVisible(true);
//            btnOpenTic.setVisible(false);
        }
    }
    private void statusClaim(){
        cbStatus.removeAllItems();
        try{
            sql="select data from _ws_status_claim ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbStatus.addItem(rs.getString(1));
            }
            cbStatus.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void couseOf(){
        condition = "";
        try {
            sql1 = "select content from _ws_cause_of_loss ";
            if ((cobid1 != null) && (!cobid1.equals(""))){
                condition = "where bsn_id=" + cobid1 + "";
            }
            sql1 += condition;
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbCause.addItem(rs.getString(1));
            }
            cbCause.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void tpl(){
        cbTpl.removeAllItems();
        try{
            sql="select data from _ws_tpl_type ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbTpl.addItem(rs.getString(1));
            }
            cbTpl.setSelectedIndex(0);
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void typeOf(){
        cbType.removeAllItems();
        try{
            sql="select data from _ws_type_of_loss ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbType.addItem(rs.getString(1));
            }
            cbType.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void getbranch(){
        branchid="";
        try{
            sql="select branch_id from _ws_branch where name='"+cbBranch.getSelectedItem()+"'";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                branchid=(rs.getString(1).toString());
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void getTypeOf(){
        typofid="";
        try{
            sql="select code from _ws_type_of_loss where name='"+cbType.getSelectedItem()+"'";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                typofid =(rs.getString(1).toString());
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void getCouseOf(){
        causeid="";
        try{
            sql="select couseofloss_id from _ws_cause_of_loss where content='"+cbCause.getSelectedItem()+"' and bsn_id=" + cobid1 + "";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                causeid =(rs.getString(1).toString());
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void getstatus(){
        statusid="";
        try{
            sql="select code from _ws_status_claim where data='"+cbStatus.getSelectedItem()+"'";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                statusid=(rs.getString(1).toString());
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void getRegDate(){
        RegDate="";
        try{
            sql="select DATE_FORMAT(CURRENT_DATE,'%d-%b-%Y'),time_format(CURRENT_TIME,'%H:%i')";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                RegDate=(rs.getString(1).toString());
                RegTime=(rs.getString(2).toString());
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
     
}
